// Mock token generator for demo (in production, call your backend)
export function generateMockAgoraToken(
  appId: string,
  channel: string,
  uid: number = 0
): string {
  // This is a mock token for demo purposes
  // In production, this should be generated by your backend using RTC token builder
  return `mock_token_${appId}_${channel}_${uid}_${Date.now()}`;
}

// Helper to generate token from backend
export async function getAgoraToken(
  channel: string,
  uid?: number
): Promise<string> {
  try {
    const response = await fetch('/api/agora/generate-token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ channel, uid: uid || 0 }),
    });

    if (!response.ok) {
      throw new Error('Failed to get Agora token');
    }

    const data = await response.json();
    return data.token;
  } catch (error) {
    console.error('[v0] Error getting Agora token:', error);
    throw error;
  }
}
